apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
        - name: docker-registry-pod
          image: registry:2.6.2
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: registry-vol
              mountPath: /var/lib/registry
            - name: registry-secret
              mountPath: /etc/docker/registry/
              readOnly: true
      volumes:
        - name: registry-vol
          persistentVolumeClaim:
            claimName: docker-registry-pvc
        - name: registry-secret
          secret:
            secretName: docker-registry
