apiVersion: v1
kind: Pod
metadata:
  name: docker-registry-pod
  labels:
    app: registry
spec:
  containers:
  - name: registry
    image: registry:2.6.2
    volumeMounts:
    - name: repo-vol
      mountPath: "/var/lib/registry"
    - name: repo-configmap
      mountPath: /etc/docker/registry
      readOnly: true
  volumes:
  - name: repo-vol
    persistentVolumeClaim:
      claimName: docker-repo-pvc
  - name: repo-configmap
    configMap:
      name: docker-registry
      items:
        - key: registry-config.yml
          path: config.yml
