apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-pvc
  namespace: docker-registry
spec:
  storageClassName: hostpath-docker-registry
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
